version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    # https://stackoverflow.com/a/24405687/11379938
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s 
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db